inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Style/EmptyCaseCondition:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 124
  AllowURI: true
  URISchemes:
    - http
    - https
  IgnoredPatterns: ['\A(?:\s)*?#']

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
