version: 2
jobs:
  build: &build
    docker:
      - image: cimg/ruby:latest
    working_directory: /home/circleci/app
    steps:
      - checkout
      - run:
          name: Install gems
          command: bundle install
      - run:
          name: Rubocop
          command: rubocop
      - run:
          name: YARDoc
          command: yardoc --fail-on-warning lib
      - run:
          name: RSpec
          command: rspec
  ruby-2.6:
    <<: *build
    docker:
      - image: cimg/ruby:2.6
  ruby-2.7:
    <<: *build
    docker:
      - image: cimg/ruby:2.7
  ruby-3.0:
    <<: *build
    docker:
      - image: cimg/ruby:3.0

workflows:
  version: 2
  build-using-multi-rubies:
    jobs:
      - ruby-2.6
      - ruby-2.7
      - ruby-3.0
